# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'

    - name: Build
      run: go build -v -o server ./cmd/server/main.go
  
    - name: Deploy
      uses: imajeetyadav/rsync-deployer@2.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source_path: ./server
        target_path: /var/www/wx-miniprogram-backend/
        delete_option: true
        print_summary: true
        print_statistics: true
        debug: false